# -*- coding: utf-8 -*-

TARGETDIR = r'./AbLab_Rpts'
import os

start_directory = TARGETDIR  # Start from the target directory

print(f"Walking through directory: {os.path.abspath(start_directory)}\n")
# Iterate over the 3-tuples generated by os.walk()
for dirpath, dirnames, filenames in os.walk(start_directory):
    # Print the current directory path
    print(f"Current Directory: {dirpath}")
    
    # List subdirectories found
    if dirnames:
        print(f"  Subdirectories: {', '.join(dirnames)}")

    # Iterate over files in the current directory
    for filename in filenames:
        # Construct and print the full path of each file
        full_file_path = os.path.join(dirpath, filename)
        print(f"  Found file: {full_file_path}")
    print("-" * 40)
    
