# -*- coding: utf-8 -*-
"""
Created on Thu Dec 18 15:32:19 2025

@author: dowes
"""

WORKINGDIR = r'C:\Users\dowes\OneDrive\Projects\LabReports'
TARGETDIR = r'./AbLab_Rpts'
OUTPUTDIR = r'./Output'

itr = '02'

import os

form_feed = '\f'
form_feed_count = 0
line_count = 0

def process_line(f_in):
    global line_count, form_feed_count
    for line in f_in:
        line_count += 1
        if form_feed in line:
            form_feed_count += 1
        
        
    

start_directory = TARGETDIR  # Start from the target directory

print(f"Walking through directory: {os.path.abspath(start_directory)}\n")
# Iterate over the 3-tuples generated by os.walk()
for dirpath, dirnames, filenames in os.walk(start_directory):
    # Print the current directory path
    print(f"Current Directory: {dirpath}")
    
    # List subdirectories found
    if dirnames:
        print(f"  Subdirectories: {', '.join(dirnames)}")

    # Iterate over files in the current directory
    for filename in filenames:
        # Construct and print the full path of each file
        full_file_path = os.path.join(dirpath, filename)
        file_in = open(full_file_path, 'r')
        print(f"  File opened: {full_file_path}")
        process_line(file_in)
        file_in.close()

    print("-" * 40)
    
print(line_count, form_feed_count) 
